### ISSUE TITLE
SCITT COSE Envelope Viewer

### ISSUE THREAD

**Issue by OR13** [scitt-community/governance#10]
I built https://github.com/OR13/v.gluecose.org based on https://github.com/gluecose/cose-viewer

The idea was to make it easy to share COSE examples, similar to how jwt.io works.

It would be helpful to use this to share examples of claims and receipts as they evolve.

If folks would like this tiny github pages powered preview site donated, I am happy to donate.

**Comment by letmaik** [comment]
@OR13 I think that would be great, and thanks for putting in the work to make it run as static page on GitHub as well! Having it as a SCITT community project would also allow us to easily add things specific to SCITT.

**Comment by mprorock** [comment]
+1 would love to see this transferred in

**Comment by kaywilliams** [comment]
+1

**Comment by SteveLasker** [comment]
+1 to make it super easy for people to keep their COSE content as binary for efficient transport, but use this tool to view it as text for humans.

**Comment by SteveLasker** [comment]
Suggest defining a CODEOWNERS file, setting the license to MIT before transferring.

**Comment by yogeshbdeshpande** [comment]
+1

**Comment by JAG-UK** [comment]
+1

**Comment by SteveLasker** [comment]
Congrats @OR13, you have a majority vote. 
If you could prep the CODEOWNERS and License, please go ahead and transfer the repo to: https://github.com/scitt-community/
For now, any existing CODEOWNERS you've used in your team would be great, and we can add new maintainers as needed through the [scitt-community governance](https://github.com/scitt-community/governance/tree/main/org-docs)

You're call if you'd like to add the [governance template files](https://github.com/scitt-community/governance/tree/main/project-doc-templates) before or after transference.

**Comment by cabo** [comment]
Nice.  I had been thinking about defining a "diagnostic notation" for COSE, which of course is going to be a little more complex than CBOR diagnostic notation.  A site like https://cbor.me would be next...

**Comment by OR13** [comment]
@cabo yes, I was hoping for something like a mixture of YAML / JSON with references to registries... A risk of just using JSON is that works will confuse JOSE and COSE.

**Comment by OR13** [comment]
I did the transfer, the repo is now here: https://github.com/scitt-community/v.gluecose.org
