### ISSUE TITLE
Create an `examples` repo for SCITT Statements, Signed Statements, Receipts

### ISSUE THREAD

**Issue by SteveLasker** [scitt-community/governance#14]
As a comparison: https://github.com/cose-wg/Examples/

**Comment by SteveLasker** [comment]
I like the directory of source/examples to use. Users could then use the [emulator](https://github.com/scitt-community/scitt-api-emulator/) or scitt.xyz to test them, then PR back back the results for comparison.
Being able to include a readme.md file explaining the usecase/scenario could provide the additional context.

**Comment by OR13** [comment]
perhaps:

https://github.com/scitt-community/scitt-examples

README
scripts (so examples can be refreshed by CLI)
examples/

under examples grouping by use case or document type?

Use case could look like:

container-provenance/ (container image related files) (statement, signed-statement, receipt, transparent-statement)
food-safety/ (food safety related files) 
mineral-supply-chain/ (mineral examples)

document type would look like:

statements / (all use cases)
signed-statements / (all use cases)
receipts / (all use cases)
transparent-statements / (all use cases)

I prefer the use case structure for this, I think it will be easier for people to understand.

**Comment by SteveLasker** [comment]
Agree on grouping by the use case as there could be a description that shows the files in particular workflow/scenarios uder that use case.

**Comment by yogeshbdeshpande** [comment]
@SteveLasker Thank you for bringing this up! 

100% aligned with your thought process. Examples is a great way to demonstrate the concepts.

Directory structure alignment, I have no hard views, so long as it fits logically, I am ok with any convention, you lay down.

**Comment by SteveLasker** [comment]
Thanks, @OR13, @yogeshbdeshpande 
Created: https://github.com/scitt-community/scitt-examples
