### ISSUE TITLE
Add py-scrapi Project

### ISSUE THREAD

**Issue by SteveLasker** [scitt-community/governance#19]
DataTrails would like to donate [ScraPy](https://github.com/JAG-UK/ScraPy) to the SCITT community
ScraPy is a Python implementation of the [SCRAPI](https://datatracker.ietf.org/doc/draft-ietf-scitt-scrapi/) draft.

Referencing the [SCITT Community Governance](https://github.com/scitt-community/governance/blob/main/org-docs/CHARTER.md#8-project-criteria)

Please 👍 if you approve, with details for why not.

**Comment by SteveLasker** [comment]
+1 from Orie to adopt

@aj-stein mentioned [ScraPy is an existing web crawling Python Package](https://pypi.org/project/Scrapy/).

I'd suggest we separate the adoption of the SCRAPI Python Package to the SCITT Community, and the name, which we can change. 

Please vote for adoption, and a proposal for a name.

Other SCITT Packages
- [scrapi](https://pypi.org/project/scrapi/) - not recently maintained, but existing
- [pyscitt](https://pypi.org/project/pyscitt/) for the Microsoft CCF implementation, but not SCRAPI
- [datatrails-receipt-scitt](https://pypi.org/project/datatrails-receipt-scitt/)
- [rkvst-receipt-scitt](https://pypi.org/project/rkvst-receipt-scitt/) - ahh, the fun renaming...

Open to suggestions:
- [ ] [scrapi-py](https://pypi.org/search/?q=scrapi-py)
- [ ] [scitt-scrapi](https://pypi.org/search/?q=scitt-scrapi)

**Comment by aj-stein** [comment]
To confirm I am happy to adopt the project as part of the community, but I would recommend a name change.

And thanks for catching me, Steve, I confused scrapi and scapy (the latter for packet capture) but yes from the supply chain focus of our community, duplicating the former is probably not so good.

**Comment by JAG-UK** [comment]
> @aj-stein mentioned [ScraPy is an existing web crawling Python Package](https://pypi.org/project/Scrapy/).

Nooooo! :(

> I'd suggest we separate the adoption of the SCRAPI Python Package to the SCITT Community, and the name, which we can change.

Assuming the adoption vote passes I'll happily rename it before landing here.
There are lots of "scrapi" and "scrapi" packages up on pypi. I'm most tempted to stick with the convention of pycose, gocose et al, and name it pyscrapi. But scitt-scrapi is fine with me too.

**Comment by SteveLasker** [comment]
I've added pyscrapi as an option to the list.

**Comment by SteveLasker** [comment]
Added: https://github.com/scitt-community/py-scrapi
