### ISSUE TITLE
Transfer the git repo for scitt.io 

### ISSUE THREAD

**Issue by SteveLasker** [scitt-community/governance#7]
With the SCITT Community now formed, this is a vote for the steering committee to transfer the https://github.com/ietf-scitt/scitt-web/ repo under the https://github.com/scitt-community/ org

**Comment by kaywilliams** [comment]
+1

**Comment by OR13** [comment]
+1

**Comment by mprorock** [comment]
+1

**Comment by SteveLasker** [comment]
With 4 out of 7 voted, we have a majority. Transfering scitt.io to the scitt-community was captured in the charter, so this was more of a formality. I'll transfer in time for the SCITT community meeting tomorrow.
