### ISSUE TITLE
Transfer the API Emulator to scitt-community

### ISSUE THREAD

**Issue by SteveLasker** [scitt-community/governance#8]
With the SCITT Community formed, this is a vote for the steering committee to accept the donation from Microsoft for the https://github.com/microsoft/scitt-api-emulator to move under the https://github.com/scitt-community/ org

**Comment by SteveLasker** [comment]
+1

**Comment by kaywilliams** [comment]
+1

**Comment by OR13** [comment]
+1

**Comment by mprorock** [comment]
+1

**Comment by SteveLasker** [comment]
Completed: https://github.com/scitt-community/scitt-api-emulator
