### ISSUE TITLE
Where to initiate PRs from

### ISSUE THREAD

**Issue by SteveLasker** [scitt-community/governance#9]
I've noticed folks either:
- Create a branch in the https://github.com/scitt-community/[repo] or 
- Create a branch in their fork of the https://github.com/scitt-community/[repo]

Creating a branch within the scitt-community isn't necessarily available to everyone, and it leaves a bunch of branches behind that must be cleaned up.

How do folks feel about creating PR guidance for establishing PRs from forks, and disabling the ability to create branches on the https://github.com/scitt-community/ repos?

**Comment by kaywilliams** [comment]
As long as there is clear guidance, requiring forks works for me.

**Comment by mprorock** [comment]
> How do folks feel about creating PR guidance for establishing PRs from forks, and disabling the ability to create branches on the https://github.com/scitt-community/ repos?

big +1 (as someone guilty of leaving things behind for people to clean up)

I also think setting rebase + merge as default etc is also a good thing
